### ISSUE TITLE
Display req/s instead of total requests

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/website#11]
Hi,

I can see that total requests are displayed on https://web-frameworks-benchmark.netlify.app/result by default.

I think `req/s` has more meaning.

Regards,

**Comment by SuspiciousLookingOwl** [comment]
Should I replace `total request` with `req/s`, or should I just add `req/s` so it display both `total request` and `req/s` separately?

**Comment by waghanza** [comment]
I think replacing, for me `total requests` has no real meaning for an analysis

**Comment by SuspiciousLookingOwl** [comment]
👍🏻 `req/s` is just `totalRequest / duration` right?

**Comment by waghanza** [comment]
yes. this data is already exposed `total_requests_per_s`
