### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/website#13]
Hi @SuspiciousLookingOwl,

Perhaps it is a good idea to sort result (by default). It could be a good idea to keep the same sorting as actual `README`, by `req/s` on **64** concurrency level.

Regards,

**Comment by SuspiciousLookingOwl** [comment]
FYI this is actually fixed on #16 (https://github.com/the-benchmarker/website/pull/16/commits/b67e6edda14f7a4d3dcb0710c97480164954e250), not https://github.com/the-benchmarker/website/commit/22379b66046dc34ce39b8c24719c582aed3d9cee 😂
