### ISSUE TITLE
Display errors

### ISSUE THREAD

**Issue by waghanza** [the-benchmarker/website#14]
Hi,

In `json` their is many `..._errors` keys (http or socket based).

It could be accurate to add this information on UI.

The main question is how.

Regards,

PS : The errors are already remove from `req/s` in https://github.com/the-benchmarker/web-frameworks/blob/53cbf2e70a773ff82bae600e218192a012e01eab/.tasks/db.rake#L22

**Comment by SuspiciousLookingOwl** [comment]
There are `http_errors`, `socket_connection_errors`, `socket_read_errors`, `socket_write_errors`. Should we show them all?

**Comment by waghanza** [comment]
I think we should separate this in 2 :
- display http errors is in this page (only if >0) => more for framework users
- have a more details page => more for framework creators

**Comment by SuspiciousLookingOwl** [comment]
> display http errors is in this page (only if >0) => more for framework users

How about this?

![image](https://user-images.githubusercontent.com/32597776/116565742-55ec3580-a930-11eb-9414-082351896719.png)

If there's any `http_errors` on any concurrencies, it will show something next to the framework name (I use red dot for this example, I can change it to icon or something else), then people can hover it and it will shows the `http_errors` count

**Comment by waghanza** [comment]
awesome

**Comment by SuspiciousLookingOwl** [comment]
> have a more details page => more for framework creators

This will be tracked in #19
