### ISSUE TITLE
Missing Spring Data

### ISSUE THREAD

**Issue by imliuyzh** [the-benchmarker/website#23]
For some reasons, nothing show up on the website when I selected "Spring":
![screenshot](https://user-images.githubusercontent.com/50005255/147418586-19013e98-bd70-49d1-b90f-e9d026fe43b7.jpeg)

**Comment by waghanza** [comment]
Thanks for your interest @imliuyzh.

`spring` has failed on the last update. This will be solved on the next round, in about 15 hours
