### ISSUE TITLE
`Result` page not showing 

### ISSUE THREAD

**Issue by Rafat97** [the-benchmarker/website#28]
When in visit https://web-frameworks-benchmark.netlify.app/result. It's occur an error. And gives a white screen. I gave a screenshot for that- 

![shot_220611_164526](https://user-images.githubusercontent.com/21246862/173184583-92dbc892-93d7-4469-8e42-8d52d5b7a41e.png)

**Comment by waghanza** [comment]
Yep, I've seen that. It is fixed now

**Comment by Rafat97** [comment]
Awesome.
