### ISSUE TITLE
use your database

### ISSUE THREAD

**Issue by igifar** [the-benchmarker/website#36]
hi
How can I use your data for myself and on my site? I need your database on my host.

thank you very much

**Comment by SuspiciousLookingOwl** [comment]
Hi, there's no database used on the website.

The website read the generated [json](https://raw.githubusercontent.com/the-benchmarker/web-frameworks/master/data.min.json) data from the [web-frameworks](https://github.com/the-benchmarker/web-frameworks) repository.
