### ISSUE TITLE
Add Iris Framework in comparation list

### ISSUE THREAD

**Issue by anboo44** [the-benchmarker/website#39]
The Iris is a Golang Framework with repository at here: https://github.com/kataras/iris
Please add it. Thank you so much

**Comment by waghanza** [comment]
Hi @anboo44,

Thanks for your proposal. However, there is an history track about `iris`
@see https://github.com/the-benchmarker/web-frameworks/issues/1129 and https://github.com/the-benchmarker/web-frameworks/issues/1158

I will **NOT** re-introduce `iris` here, the decision has been taken as a community :heart: 

There is also https://github.com/the-benchmarker/web-frameworks/issues/1138
