### ISSUE TITLE
Add framework Ntex for Rust

### ISSUE THREAD

**Issue by rainyEra** [the-benchmarker/website#41]
Hello, can you add ntex for Rust? Thanks!
https://github.com/ntex-rs/ntex

**Comment by waghanza** [comment]
Hi @rainyEra,

Thanks for asking.


I'm afraid the author do not want to be included in this list
https://github.com/the-benchmarker/web-frameworks/issues/5284

Feel free to re-open the above issue and to ping some contributors to have no explicit opposition on adding `ntex` in this list.

Regards,
