### ISSUE TITLE
The list lacks Bitrix 

### ISSUE THREAD

**Issue by Kabingeran** [the-benchmarker/website#49]
Hello. I didn't see Bitrix in the list

**Comment by waghanza** [comment]
Then feel free to add it ❤️

**Comment by waghanza** [comment]
The PR should be done in `web-frameworks` project

**Comment by waghanza** [comment]
I close this one, feel free to make à heads up in https://github.com/the-benchmarker/web-frameworks/issues/7360 @Kabingeran
