### ISSUE TITLE
add next.js

### ISSUE THREAD

**Issue by gengjiawen** [the-benchmarker/website#50]
Repo: https://nextjs.org/

**Comment by waghanza** [comment]
Hi @gengjiawen ,

This project is more backend  benchmark. 

Could nextjs play in this category ?

The idea is to build an API, as far as I understand, nextjs is more for frontend stuff, no ?

Regards,

**Comment by gengjiawen** [comment]
> The idea is to build an API, as far as I understand, nextjs is more for frontend stuff, no ?

It's a fullstack framework. Has full backend support.
