### ISSUE TITLE
add average cpu/memory usage

### ISSUE THREAD

**Issue by rxdiscovery** [the-benchmarker/website#51]
Hello,

Thanks for this great site, I'd like to know if it's possible to add average CPU and memory usage to the measurement data, as it's also very important.

thanks in advance.

**Comment by waghanza** [comment]
Hello,

Yes, this is planned. 

Not an easy task todo, I mean since the arch used for the project zill change after stabilization.

If you whish to participate, be my guest.

Rather use `web-frameworks` project in this organisation.
