### ISSUE TITLE
Show old benchmark data (Benchmark History)

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [the-benchmarker/website#9]
Hi @waghanza, I had an idea of showing old benchmark data.

How it works:
1. Get file history of `data.min.json` from https://api.github.com/repos/the-benchmarker/web-frameworks/commits?path=data.min.json
2. Get distinct commit date from the history, and show it as dropdown select on the website linked to the commit's sha
3. Fetch data based on the selected date using the commit's sha (e.g. `https://raw.githubusercontent.com/the-benchmarker/web-frameworks/${sha}/data.min.json` (You can use full SHA or first 7 characters of SHA for `${sha}`)

What do you think?

**Comment by waghanza** [comment]
Sure, it will be a great addition. 

However :
+ display SHA make no sense (for readers), better to display date of commits
+ better to wait for stability (I mean framework X could fail at commit SHA)

**Comment by SuspiciousLookingOwl** [comment]
> display SHA make no sense (for readers), better to display date of commits

Yep that was I meant, my mistake I wasn't clear enough 😅 

> better to wait for stability (I mean framework X could fail at commit SHA)

I think commits from https://api.github.com/repos/the-benchmarker/web-frameworks/commits?path=data.min.json are commits that get merged to master. If it's merged to master doesn't mean that the benchmark has run successfully?

**Comment by waghanza** [comment]
Unfortunately not, merge commits could have failures (for example, a `PR` is started by `renovatebot` to update framework X in language Y, but framework Z is failing in this language Y, not due to this `PR` but failure is revealed by this `PR`, so I merge the `PR` into master and I start a new one for framework Z)

**Comment by SuspiciousLookingOwl** [comment]
But https://api.github.com/repos/the-benchmarker/web-frameworks/commits?path=data.min.json only shows commits that modifies `data.min.json` file, and AFAIK PR that modifies `data.min.json` are only PR that made manually by you [like this](https://github.com/the-benchmarker/web-frameworks/commits/master/data.min.json)

**Comment by waghanza** [comment]
OK. Then those commits are safe 👍🏻
